### ISSUE TITLE
Fixing the UI box

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-figma#21]
Current State: Currently the eos-icons have a UI box which is bigger in size.
![image](https://user-images.githubusercontent.com/67755381/158222431-e543b4df-f789-4ae6-9ecb-21d460f635d2.png)
Expected State: The UI box should have smaller width to height ratio as it is consuming a lot of figma file page.

**Comment by AnshumanDhiman** [comment]
I would like to work on this

**Comment by iamAbhishekkumar** [comment]
> I would like to work on this 
> 

Sorry, I am already working on UI improvement. : )

**Comment by iamAbhishekkumar** [comment]
> > I would like to work on this 
> > 
> 
> Sorry, I am already working on UI improvement. : )

@AnshumanDhiman
