### ISSUE TITLE
All  state not showing all icons in Theme Dropdown

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-figma#24]
Current State:
The current theme dropdown in the plugin is set to All. But whenever a user loads the plugin only Filled icons gets loaded. If a user selects another theme and then switch back to All theme then it works and loads all the icons.

https://user-images.githubusercontent.com/67755381/158421243-be824449-9afc-4a61-9037-80c72104361e.mp4

Expected State: 
When all theme is selected all icons should be shown in the present view.

**Comment by AnshumanDhiman** [comment]
I would like to work on this issue.

**Comment by iamAbhishekkumar** [comment]
Duplicate of #23

**Comment by AnshumanDhiman** [comment]
Didn't saw that, thanks for mentioning.
